sync

diff --git a/utils/watchcat/files/watchcat.init b/utils/watchcat/files/watchcat.init
--- a/utils/watchcat/files/watchcat.init
+++ b/utils/watchcat/files/watchcat.init
@@ -32,6 +32,7 @@ time_to_seconds() {
 
 config_watchcat() {
 	# Read config
+	config_get_bool enabled "$1" enabled 1
 	config_get period "$1" period "120"
 	config_get mode "$1" mode "ping_reboot"
 	config_get pinghosts "$1" pinghosts "8.8.8.8"
@@ -39,10 +40,13 @@ config_watchcat() {
 	config_get forcedelay "$1" forcedelay "60"
 	config_get pingsize "$1" pingsize "standard"
 	config_get interface "$1" interface
-	config_get mmifacename "$1" mmifacename
+	config_get mmifacename "$1" mmifacename "null"
 	config_get_bool unlockbands "$1" unlockbands "0"
 	config_get addressfamily "$1" addressfamily "any"
 	config_get script "$1" script
+
+	# Skip disabled instances
+	[ "$enabled" = 1 ] || return
 
 	# Fix potential typo in mode and provide backward compatibility.
 	[ "$mode" = "allways" ] && mode="periodic_reboot"
@@ -73,7 +77,7 @@ config_watchcat() {
 				append_string "warn" "pingperiod cannot be a negative value." "; "
 			fi
 
-			if [ "$mmifacename" != "" ] && [ "$period" -lt 30 ]; then
+			if [ "$mmifacename" != "null" ] && [ "$period" -lt 30 ]; then
 				append_string "error" "Check interval is less than 30s. For robust operation with ModemManager modem interfaces it is recommended to set the period to at least 30s."
 			fi
 		fi
@@ -90,40 +94,35 @@ config_watchcat() {
 
 	[ -n "$warn" ] && logger -p user.warn -t "watchcat" "$1: $warn"
 	[ -n "$error" ] && {
-		logger -p user.err -t "watchcat" "reboot program $1 not started - $error"
+		logger -s -p user.err -t "watchcat" "reboot program $1 not started - $error"
 		return
 	}
+
+	procd_open_instance "watchcat_${1}"
 
 	# Need to conditionally run mode functions because they have different signatures
 	case "$mode" in
 	periodic_reboot)
-		procd_open_instance "watchcat_${1}"
 		procd_set_param command /usr/bin/watchcat.sh "periodic_reboot" "$period" "$forcedelay"
-		procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
-		procd_close_instance
 		;;
 	ping_reboot)
-		procd_open_instance "watchcat_${1}"
-		procd_set_param command /usr/bin/watchcat.sh "ping_reboot" "$period" "$forcedelay" "$pinghosts" "$pingperiod" "$pingsize" "$addressfamily"
-		procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
-		procd_close_instance
+		procd_set_param command /usr/bin/watchcat.sh "ping_reboot" "$period" "$forcedelay" "$pinghosts" "$pingperiod" "$pingsize" "$addressfamily" "$interface"
 		;;
 	restart_iface)
-		procd_open_instance "watchcat_${1}"
 		procd_set_param command /usr/bin/watchcat.sh "restart_iface" "$period" "$pinghosts" "$pingperiod" "$pingsize" "$interface" "$mmifacename" "$unlockbands" "$addressfamily"
-		procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
-		procd_close_instance
 		;;
 	run_script)
-		procd_open_instance "watchcat_${1}"
 		procd_set_param command /usr/bin/watchcat.sh "run_script" "$period" "$pinghosts" "$pingperiod" "$pingsize" "$interface" "$addressfamily" "$script"
-		procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
-		procd_close_instance
 		;;
-	*)
-		echo "Error starting Watchcat service. Invalid mode selection: $mode"
-		;;
+	# *)  # impossible case, mode checked above.
+	#	;;
 	esac
+
+	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
+	# simplify debugging
+	procd_set_param stdout 1
+	procd_set_param stderr 1
+	procd_close_instance
 }
 
 start_service() {
