sync

diff --git a/net/miniupnpd/files/miniupnpd.init b/net/miniupnpd/files/miniupnpd.init
--- a/net/miniupnpd/files/miniupnpd.init
+++ b/net/miniupnpd/files/miniupnpd.init
@@ -7,113 +7,65 @@ USE_PROCD=1
 PROG=/usr/sbin/miniupnpd
 [ -x "$(command -v nft)" ] && FW="fw4" || FW="fw3"
 
-upnpd_get_port_range() {
-	local var="$1"; shift
-	local val
-
-	config_get val "$@"
-
-	case "$val" in
-		[0-9]*[:-][0-9]*)
-			export -n -- "${var}_start=${val%%[:-]*}"
-			export -n -- "${var}_end=${val##*[:-]}"
-		;;
-		[0-9]*)
-			export -n -- "${var}_start=$val"
-			export -n -- "${var}_end="
-		;;
-	esac
-}
-
-conf_rule_add() {
-	local cfg="$1"
-	local action int_addr
-	local ext_start ext_end int_start int_end comment
-
-	config_get action "$cfg" action "deny"                # allow or deny
-	upnpd_get_port_range "ext" "$cfg" ext_ports "0-65535" # external ports: x, x-y, x:y
-	config_get int_addr "$cfg" int_addr "0.0.0.0/0"       # ip or network and subnet mask (internal)
-	upnpd_get_port_range "int" "$cfg" int_ports "0-65535" # internal ports: x, x-y, x:y or range
-	config_get comment "$cfg" comment "ACL"		      # comment
-
-	# Make a single IP IP/32 so that miniupnpd.conf can use it.
-	[ "${int_addr%/*}" = "$int_addr" ] && int_addr="$int_addr/32"
-
-	echo "$action $ext_start${ext_end:+-}$ext_end $int_addr $int_start${int_end:+-}$int_end #$comment"
-}
-
-upnpd_write_bool() {
-	local opt="$1"
-	local def="${2:-0}"
-	local alt="${3:-$opt}"
-	local val
-
-	config_get_bool val config "$opt" "$def"
-	if [ "$val" -eq 0 ]; then
-		echo "$alt=no"
-	else
-		echo "$alt=yes"
-	fi
-}
-
 upnpd() {
 	config_load "upnpd"
-	local external_iface external_iface6 external_zone external_ip internal_iface
-	local upload_kbps download_kbps log_output port config_file serial_number model_number
-	local use_stun stun_host stun_port uuid notify_interval presentation_url
-	local upnp_lease_file clean_ruleset_threshold clean_ruleset_interval
-
 	local enabled
+	config_get enabled settings enabled 0
+	[ "$enabled" != "1" ] && log "Service disabled" && return 0
 
-	config_get_bool enabled config enabled 0
-	[ $enabled -gt 0 ] || return 1
+	# Daemon
+	local enabled_protocols acl_reject_unsafe_ports allow_cgnat_use stun_host allow_third_party_mapping ipv6_disable system_uptime log_output lease_file config_file
+	config_get enabled_protocols settings enabled_protocols all
+	config_get acl_reject_unsafe_ports settings acl_reject_unsafe_ports "21 23 135 137-139 445 3389"
+	config_get allow_cgnat_use settings allow_cgnat_use 0
+	config_get stun_host settings stun_host stun.nextcloud.com
+	config_get allow_third_party_mapping settings allow_third_party_mapping 0
+	config_get ipv6_disable settings ipv6_disable 0
+	config_get system_uptime settings system_uptime 1
+	config_get log_output settings log_output
+	config_get lease_file settings lease_file /var/run/miniupnpd.leases
+	config_get config_file settings config_file
 
-	config_get external_iface config external_iface
-	config_get external_iface6 config external_iface6
-	config_get external_zone config external_zone
-	config_get external_ip config external_ip
-	config_get internal_iface config internal_iface
-	config_get port config port 5000
-	config_get upload_kbps config upload_kbps
-	config_get download_kbps config download_kbps
-	config_get_bool log_output config log_output 0
-	config_get config_file config config_file
-	config_get serial_number config serial_number
-	config_get model_number config model_number
-	config_get uuid config uuid
-	config_get use_stun config use_stun 0
-	config_get stun_host config stun_host
-	config_get stun_port config stun_port
-	config_get notify_interval config notify_interval
-	config_get presentation_url config presentation_url
-	config_get upnp_lease_file config upnp_lease_file
-	config_get clean_ruleset_threshold config clean_ruleset_threshold
-	config_get clean_ruleset_interval config clean_ruleset_interval
-	config_get_bool allow_third_party_maps config allow_third_party_maps 0
-	config_get upnp_igd_compat config upnp_igd_compat igdv1
-	config_get force config force 0
+	# UPnP IGD
+	local upnp_igd_compat upnp_igd_download upnp_igd_upload upnp_igd_friendly_name model_number serial_number presentation_url uuid upnp_igd_http_port notify_interval
+	config_get upnp_igd_compat settings upnp_igd_compat igdv1
+	config_get upnp_igd_download settings upnp_igd_download
+	config_get upnp_igd_upload settings upnp_igd_upload
+	config_get upnp_igd_friendly_name settings upnp_igd_friendly_name
+	config_get model_number settings model_number
+	config_get serial_number settings serial_number
+	config_get presentation_url settings presentation_url
+	config_get uuid settings uuid
+	config_get upnp_igd_http_port settings upnp_igd_http_port 5000
+	config_get notify_interval settings notify_interval
+	config_get force settings force 0
+
+	# External network interface
+	local external_iface external_iface6 external_zone external_ip
+	config_get external_iface settings external_iface
+	config_get external_iface6 settings external_iface6
+	config_get external_zone settings external_zone
+	config_get external_ip settings external_ip
 
 	local conf ifname ifname6
-
 	. /lib/functions/network.sh
-
-	if [ -n "$external_iface" ] ; then
+	if [ -n "$external_iface" ]; then
 		network_get_device ifname "$external_iface"
 	else
-		if [ -n "$external_zone" ] ; then
+		if [ -n "$external_zone" ]; then
 			ifname=$($FW -q zone "$external_zone" 2>/dev/null | head -1)
 		else
-			network_find_wan external_iface && \
+			network_find_wan external_iface &&
 				network_get_device ifname "$external_iface"
 		fi
 	fi
-	if [ -n "$external_iface6" ] ; then
+	if [ -n "$external_iface6" ]; then
 		network_get_device ifname6 "$external_iface6"
 	else
-		if [ -n "$external_zone" ] ; then
+		if [ -n "$external_zone" ]; then
 			ifname6=$($FW -q zone "$external_zone" 2>/dev/null | head -1)
 		else
-			network_find_wan6 external_iface6 && \
+			network_find_wan6 external_iface6 &&
 				network_get_device ifname6 "$external_iface6"
 		fi
 	fi
@@ -124,97 +76,108 @@ upnpd() {
 		local tmpconf="/var/etc/miniupnpd.conf"
 		conf="$tmpconf"
 		mkdir -p /var/etc
+		[ "$ifname" = "" ] && log "No external network interface found, not starting" daemon.err && return 0
+		! uci -q get upnpd.@internal_network[0].interface >/dev/null && log "No internal network interface configured, not starting" daemon.err && return 0
 
 		{
-		echo "ext_ifname=$ifname"
-		echo "ext_ifname6=$ifname6"
-		[ -n "$external_ip" ] && echo "ext_ip=$external_ip"
+			echo "# Daemon"
+			{ [ "$enabled_protocols" = "upnp-igd" ] || [ "$enabled_protocols" = "all" ]; } && echo "enable_upnp=yes" || echo "enable_upnp=no"
+			{ [ "$enabled_protocols" = "pcp+nat-pmp" ] || [ "$enabled_protocols" = "all" ]; } && echo "enable_pcp_pmp=yes" || echo "enable_pcp_pmp=no"
+			# Only use STUN when necessary with a private/CGNAT external IPv4
+			local extipv4 extipv4private
+			network_get_ipaddr extipv4 "$ifname"
+			case "$extipv4" in 10.* | 172.1[6-9].* | 172.2[0-9].* | 172.3[0-1].* | 192.168.* | 100.6[4-9].* | 100.[7-9][0-9].* | 100.1[0-1][0-9].* | 100.12[0-7].*)
+				extipv4private=1
+				;;
+			esac
+			if [ "$extipv4private" = "1" ] && [ "$allow_cgnat_use" != "0" ] && [ "$external_ip" = "" ]; then
+				[ "$allow_cgnat_use" = "1" ] && echo "ext_perform_stun=yes"
+				[ "$allow_cgnat_use" = "allow-filtered" ] && echo "ext_perform_stun=allow-filtered"
+				# Commented out as allow-filtered detects a public IPv4, required by some (e.g. PCP/NAT-PMP) clients
+				# [ "$allow_cgnat_use" = "allow-private-ext-ipv4" ] && external_ip=203.1.2.3
+				echo "ext_stun_host=${stun_host%%:*}"
+				[ "${stun_host%%:*}" != "${stun_host##*:}" ] && echo "ext_stun_port=${stun_host##*:}"
+			fi
+			{ [ "$allow_third_party_mapping" = "0" ] || [ "$allow_third_party_mapping" = "1" ]; } &&
+				echo_yesno_opt_inverse secure_mode "$allow_third_party_mapping" &&
+				echo_yesno_opt pcp_allow_thirdparty "$allow_third_party_mapping"
+			[ "$allow_third_party_mapping" = "upnp-igd" ] && echo "secure_mode=no" && echo "pcp_allow_thirdparty=no"
+			[ "$allow_third_party_mapping" = "pcp" ] && echo "secure_mode=yes" && echo "pcp_allow_thirdparty=yes"
+			echo_yesno_opt ipv6_disable "$ipv6_disable"
+			echo_yesno_opt system_uptime "$system_uptime"
+			echo_yesno_opt ext_allow_private_ipv4 "$force"
+			touch "$lease_file" && echo "lease_file=$lease_file"
+			[ "$ipv6_disable" = "0" ] && touch "${lease_file}-ipv6" && echo "lease_file6=${lease_file}-ipv6"
 
-		local iface
-		for iface in ${internal_iface:-lan}; do
-			local device
-			network_get_device device "$iface" && echo "listening_ip=$device"
-		done
+			if [ "$enabled_protocols" = "upnp-igd" ] || [ "$enabled_protocols" = "all" ]; then
+				echo "# UPnP IGD"
+				[ "$upnp_igd_compat" = "igdv1" ] && echo "force_igd_desc_v1=yes" || echo "force_igd_desc_v1=no"
+				[ -n "$upnp_igd_download" ] && echo "bitrate_down=$((upnp_igd_download * 1000))"
+				[ -n "$upnp_igd_upload" ] && echo "bitrate_up=$((upnp_igd_upload * 1000))"
+				[ -n "$upnp_igd_friendly_name" ] && echo "friendly_name=$upnp_igd_friendly_name"
+				echo "model_number=$model_number"
+				echo "serial=$serial_number"
+				[ -n "$presentation_url" ] && echo "presentation_url=$presentation_url"
+				[ -z "$uuid" ] && {
+					uuid="$(cat /proc/sys/kernel/random/uuid)"
+					uci set upnpd.settings.uuid="$uuid"
+					uci commit upnpd
+				}
+				[ "$uuid" != "nocli" ] && echo "uuid=$uuid" || log "Deprecated. Set uuid to 00000000-0000-0000-0000-000000000000 instead"
+				echo "http_port=$upnp_igd_http_port"
+				[ -n "$notify_interval" ] && echo "notify_interval=$notify_interval"
+			fi
 
-		config_load "upnpd"
-		upnpd_write_bool enable_pcp_pmp 1
-		upnpd_write_bool enable_upnp 1
-		if [ "$allow_third_party_maps" = "1" ]; then
-		  echo "secure_mode=no"
-		  echo "pcp_allow_thirdparty=yes"
-		else
-		  echo "secure_mode=yes"
-		  echo "pcp_allow_thirdparty=no"
-		fi
-		if [ "$upnp_igd_compat" = "igdv1" ]; then
-		  echo "force_igd_desc_v1=yes"
-		else
-		  echo "force_igd_desc_v1=no"
-		fi
-		upnpd_write_bool system_uptime 1
-		upnpd_write_bool force 0 ext_allow_private_ipv4
-		upnpd_write_bool ipv6_disable 1
+			if [ "$FW" = "fw4" ]; then
+				echo "# Firewall backend"
+				echo "upnp_table_name=fw4"
+				echo "upnp_nat_table_name=fw4"
+				echo "upnp_forward_chain=upnp_forward"
+				echo "upnp_nat_chain=upnp_prerouting"
+				echo "upnp_nat_postrouting_chain=upnp_postrouting"
+			fi
 
-		[ "$use_stun" -eq 0 ] || {
-			[ "$force" -eq 0 ] && echo "ext_perform_stun=yes"
-			[ "$force" -eq 0 ] && echo "ext_perform_stun=allow-filtered"
-			[ -n "$stun_host" ] && echo "ext_stun_host=$stun_host"
-			[ -n "$stun_port" ] && echo "ext_stun_port=$stun_port"
-		}
+			echo "# External network interface"
+			echo "ext_ifname=$ifname"
+			[ -n "$ifname6" ] && [ "$ifname" != "$ifname6" ] && echo "ext_ifname6=$ifname6"
+			[ -n "$external_ip" ] && echo "ext_ip=$external_ip"
 
-		[ -n "$upload_kbps" ] && [ -n "$download_kbps" ] && {
-			echo "bitrate_down=$((download_kbps * 1000))"
-			echo "bitrate_up=$((upload_kbps * 1000))"
-		}
+			echo "# Enabled internal networks / access control list preset"
+			local unsafeport
+			for unsafeport in $acl_reject_unsafe_ports; do
+				is_port_or_range "$unsafeport" && echo "deny $unsafeport 0.0.0.0/0 $unsafeport # Reject unsafe port" ||
+					log "Invalid port or port range ($unsafeport) in acl_reject_unsafe_ports ignored" daemon.warn
+			done
+			config_foreach upnpd_add_int_network_and_acl_preset internal_network
+			echo "# Custom ACL"
+			config_foreach upnpd_add_custom_acl_entry perm_rule
+			config_foreach upnpd_add_int_network_and_acl_preset internal_network secondrun
+			echo "deny 1-65535 0.0.0.0/0 1-65535 # Reject ACL by default"
 
-		[ -n "$upnp_lease_file" ] && touch "$upnp_lease_file" && echo "lease_file=$upnp_lease_file"
-		[ -n "$presentation_url" ] && echo "presentation_url=$presentation_url"
-		[ -n "$notify_interval" ] && echo "notify_interval=$notify_interval"
-		[ -n "$clean_ruleset_threshold" ] && echo "clean_ruleset_threshold=$clean_ruleset_threshold"
-		[ -n "$clean_ruleset_interval" ] && echo "clean_ruleset_interval=$clean_ruleset_interval"
-		[ -n "$serial_number" ] && echo "serial=$serial_number"
-		[ -n "$model_number" ] && echo "model_number=$model_number"
-		[ -n "$port" ] && echo "port=$port"
-
-		[ -z "$uuid" ] && {
-			uuid="$(cat /proc/sys/kernel/random/uuid)"
-			uci set upnpd.config.uuid="$uuid"
-			uci commit upnpd
-		}
-
-		[ "$uuid" = "nocli" ] || echo "uuid=$uuid"
-
-		config_foreach conf_rule_add perm_rule
-
-		if [ "$FW" = "fw4" ]; then
-			#When using nftables configure miniupnpd to use its own table and chains
-			echo "upnp_table_name=fw4"
-			echo "upnp_nat_table_name=fw4"
-			echo "upnp_forward_chain=upnp_forward"
-			echo "upnp_nat_chain=upnp_prerouting"
-			echo "upnp_nat_postrouting_chain=upnp_postrouting"
-		fi
-
-		} > "$tmpconf"
+		} >"$tmpconf"
 	fi
 
 	if [ -n "$ifname" ]; then
-		# start firewall
 		if [ "$FW" = "fw4" ]; then
 			nft -s -t -n list chain inet fw4 upnp_forward >/dev/null 2>&1 || fw4 reload
 		else
 			iptables -L MINIUPNPD >/dev/null 2>&1 || fw3 reload
 		fi
-	else
-		logger -t "upnp daemon" "external interface not found, not starting"
 	fi
 
 	procd_open_instance
 	procd_set_param file "$conf" "/etc/config/firewall"
 	procd_set_param command "$PROG"
 	procd_append_param command -f "$conf"
-	[ "$log_output" = "1" ] && procd_append_param command -d
+	[ "$log_output" = "info" ] && procd_append_param command -v
+	[ "$log_output" = "debug" ] && procd_append_param command -d
 	procd_close_instance
+}
+
+start_service() {
+	upnpd_uci_migration
+	config_load "upnpd"
+	config_foreach upnpd "upnpd"
 }
 
 stop_service() {
@@ -230,11 +193,84 @@ stop_service() {
 	fi
 }
 
-start_service() {
-	config_load "upnpd"
-	config_foreach upnpd "upnpd"
-}
-
 service_triggers() {
 	procd_add_reload_trigger "upnpd"
+}
+
+log() {
+	logger -s -p "${2:-daemon.notice}" -t "upnpd" "$1" || echo "upnpd: $1" >&2
+}
+
+echo_yesno_opt() {
+	[ "$2" = "1" ] && echo "$1=yes" || echo "$1=no"
+}
+
+echo_yesno_opt_inverse() {
+	[ "$2" = "1" ] && echo "$1=no" || echo "$1=yes"
+}
+
+is_port_or_range() {
+	[ "$1" = "0" ] && return 1
+	[ "$1" -ge "1" ] 2>/dev/null && [ "$1" -le "65535" ] 2>/dev/null && return 0
+	[ "$2" = "port0inrange" ] && local minport=0 || local minport=1
+	[ "${1%%-*}" -ge "$minport" ] 2>/dev/null && [ "${1%%-*}" -le "65535" ] 2>/dev/null &&
+		[ "${1##*-}" -ge "$minport" ] 2>/dev/null && [ "${1##*-}" -le "65535" ] 2>/dev/null &&
+		[ "${1##*-}" -ge "${1%%-*}" ] 2>/dev/null && return 0 || return 1
+}
+
+upnpd_add_int_network_and_acl_preset() {
+	local cfg="$1"
+	local interface acl_preset acl_custom_first
+	config_get interface "$cfg" interface
+	config_get acl_preset "$cfg" acl_preset
+	config_get acl_custom_first "$cfg" acl_custom_first
+	[ "$acl_custom_first" = "1" ] && [ "$2" != "secondrun" ] && return 0
+	[ "$acl_custom_first" != "1" ] && [ "$2" = "secondrun" ] && return 0
+	local device subnet
+	network_get_device device "$interface"
+	echo "# Enable network $interface ($device) with preset ${acl_preset:-none}${acl_custom_first:+ and check custom ACL first}"
+	echo "listening_ip=$device"
+	network_get_subnet subnet "$interface"
+	if [ "$acl_preset" = "accept-high-ports" ]; then
+		echo "allow 1024-65535 $subnet 1024-65535 # Accept high ports on $interface"
+	elif [ "$acl_preset" = "accept-high-ports+web" ]; then
+		echo "allow 1024-65535 $subnet 1024-65535 # Accept high ports on $interface"
+		echo "allow 80 $subnet 80 # Accept HTTP port on $interface"
+		echo "allow 443 $subnet 443 # Accept HTTPS port on $interface"
+	elif [ "$acl_preset" = "accept-high-ports+web+dns" ]; then
+		echo "allow 1024-65535 $subnet 1024-65535 # Accept high ports on $interface"
+		echo "allow 80 $subnet 80 # Accept HTTP port on $interface"
+		echo "allow 443 $subnet 443 # Accept HTTPS port on $interface"
+		echo "allow 53 $subnet 53 # Accept DNS port (Do53) on $interface"
+		echo "allow 853 $subnet 853 # Accept DNS port (DoT/DoQ) on $interface"
+	elif [ "$acl_preset" = "accept-all-ports" ]; then
+		echo "allow 1-65535 $subnet 1-65535 # Accept all ports on $interface"
+	elif [ "$acl_preset" != "" ]; then
+		log "Invalid preset ($acl_preset) ignored" daemon.warn
+	fi
+	if [ "$acl_preset" != "" ] && [ "$acl_custom_first" != "1" ]; then
+		echo "deny 1-65535 $subnet 1-65535 # Reject ACL by default on $interface"
+	fi
+}
+
+upnpd_add_custom_acl_entry() {
+	local cfg="$1"
+	local comment action int_addr int_ports ext_ports desc_filter
+	config_get comment "$cfg" comment "No comment"  # comment
+	config_get action "$cfg" action                 # accept/reject/disabled
+	config_get int_addr "$cfg" int_addr "0.0.0.0/0" # IPv4 or network and subnet mask (internal)
+	config_get int_ports "$cfg" int_ports "1-65535" # internal port/range: x or x-y
+	config_get ext_ports "$cfg" ext_ports "1-65535" # external port/range: x or x-y
+	config_get desc_filter "$cfg" desc_filter       # description regex filter (must be built in)
+	[ "$action" = "accept" ] && action=allow
+	[ "$action" = "reject" ] && action=deny
+	[ "$action" = "disabled" ] && return 0
+	[ "$action" = "" ] && log "Custom ACL: Entry with no action ignored" daemon.warn && return 0
+	! is_port_or_range "$int_ports" port0inrange &&
+		log "Custom ACL: Entry with invalid port or port range ($int_ports) in int_ports ignored" daemon.warn && int_ports=1-65535
+	! is_port_or_range "$ext_ports" port0inrange &&
+		log "Custom ACL: Entry with invalid port or port range ($ext_ports) in ext_ports ignored" daemon.warn && ext_ports=1-65535
+	[ "$desc_filter" != "" ] && desc_filter=" \"$desc_filter\""
+
+	echo "$action $ext_ports $int_addr $int_ports${desc_filter} # $comment"
 }
